# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-06-18 16:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tv_shows_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shows',
            old_name='newtork',
            new_name='network',
        ),
    ]
