# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-06-18 15:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tv_shows_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tv_show',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='tv_show',
            name='newtork',
        ),
        migrations.RemoveField(
            model_name='tv_show',
            name='release_date',
        ),
    ]
