# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-06-18 15:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tv_shows_app', '0002_auto_20190618_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tv_show',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
