# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-06-19 17:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tv_shows_app', '0002_auto_20190618_1141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shows',
            name='description',
        ),
        migrations.RemoveField(
            model_name='shows',
            name='network',
        ),
        migrations.RemoveField(
            model_name='shows',
            name='release_date',
        ),
        migrations.AlterField(
            model_name='shows',
            name='title',
            field=models.CharField(max_length=64),
        ),
    ]
